### ISSUE TITLE
Monthly Debt Payment issue 

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/docs.leadconduit.com#18]
The description is incorrect 
![screen shot 2015-06-04 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/8238417/7994674/d5c31dce-0ad4-11e5-9061-ac236f5f7f6f.png)

Should be as follows:

Application Monthly Debt Payments	
Desc: (paraphrasing - how much do you pay monthly against your outstanding debts)

Application Monthly Debt Payments	
Desc: How many late mortgage payments have been made?

**Comment by cgrayson** [comment]
Moved to [fields repo](https://github.com/activeprospect/leadconduit-fields/issues/55).
