### ISSUE TITLE
Zip-Codes.com logo is broken

### ISSUE THREAD

**Issue by alexj** [activeprospect/docs.leadconduit.com#19]
On docs.leadconduit.com the logo for the zip-codes.com integration is broken. Please fix the image path.

![leadconduit_integration_documentation](https://cloud.githubusercontent.com/assets/140158/8704355/1b77f9f6-2ae8-11e5-99a9-52f3e33a58a1.png)

**Comment by alexj** [comment]
This is still broken. @justinwinslow @kellym can one of you take care of this?

**Comment by kellym** [comment]
Got it fixed. Seems it was looking for `zipcodes.png`, not `zip-codes.png`.

**Comment by justinwinslow** [comment]
Creating another instance of the image with a different name seems like not the best way to manage this. I wonder why the docs don't use the entities resource. \cc @alexkwolfe

**Comment by kellym** [comment]
I was wondering if zip-codes.png could be deleted -- is that one used in the app?

**Comment by kellym** [comment]
Nevermind, answered my own question. Didn't realize it was behaving differently here -- I'd agree with @justinwinslow, seems like they should both be referencing the same image.

**Comment by justinwinslow** [comment]
Is the one the entities resource points to which populates LC client.

**Comment by kellym** [comment]
Ah, it's using the package name as the reference to the image -- so the repo should have been named `leadconduit-zip-codes`, or the alternative is for LC to reference `zipcodes`.  Not sure which would cause less damage.

**Comment by kellym** [comment]
I mean, couldn't we just change the `logo_url` in the entities to `zipcodes.png` instead of `zip-codes.png`?

**Comment by justinwinslow** [comment]
> I mean, couldn't we just change the logo_url in the Zip-codes entity to zipcodes.png instead of zip-codes.png

Yah, but that still doesn't seem like a sustainable solution. Basically this is all leaning on the notion that integration authors will always adhere to strict naming schemes for modules _and_ logos.

**Comment by justinwinslow** [comment]
Also, it seems reasonable to me that an entity logo might not even point to our S3 at some point.

**Comment by kellym** [comment]
> Also, it seems reasonable to me that an entity logo might not even point to our S3 at some point.

I'd imagine we'll always have this S3 bucket, and I think we should stick to uploading them all in the same place to avoid broken images down the road. I personally don't mind automating naming like this, but I can see how down the road it may cause another issue.  Seems like a fairly low-priority issue overall, though.

**Comment by justinwinslow** [comment]
I just meant when 3rd parties start building integrations they might point to their own logos that they can maintain. But, yah, I agree. Not a huge deal right now.
